#213 UI refactor
openworld-community/ows-events pull request #241
Opened 2023-05-31 18:11 UTC by Yulia-Kotlyarova

base input
textarea
select

2023-05-31 18:34 UTC, HugeLetters commented on frontend/assets/less/global.less
Как вам идея у тейлвинда просто украсть их базовый preflight css файл? Там очень много подобных вещей уже сразу проставлено, которые практически всегда сам потом в css фиксишь.

2023-05-31 18:39 UTC, HugeLetters requested changes

2023-05-31 18:39 UTC, HugeLetters commented on frontend/i18n/locales/ru/index.ts
>    }
Я бы поменял на какое-то более интуитивное название ключа.

2023-05-31 18:39 UTC, HugeLetters commented on frontend/components/common/ui/TextArea/TextArea.vue
Поправишь тогда на SFC синтакс по аналогии с кнопкой?

2023-05-31 18:39 UTC, HugeLetters commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
И тут тоже SFC синтакс

2023-05-31 18:47 UTC, Yulia-Kotlyarova commented on frontend/assets/less/global.less
стили пока просто накидала, чтобы криво не было, ждем редизайн
а про preflight css не совсем поняла

2023-05-31 18:48 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/TextArea/TextArea.vue
> Поправишь тогда на SFC синтакс по аналогии с кнопкой?

SFC это ключ перевода?

2023-05-31 18:53 UTC, Yulia-Kotlyarova commented on frontend/i18n/locales/ru/index.ts
>    }
> Я бы поменял на какое-то более интуитивное название ключа.

мб buttonCTA? clickCTA? actionCTA? выбирай предлагай)

2023-05-31 18:54 UTC, HugeLetters commented on frontend/components/common/ui/TextArea/TextArea.vue
Single File Component - сори, я думал, тут где-то будут написаны комментарии к моему [коммиту](https://github.com/openworld-community/ows-events/pull/241/commits/1e33648416f561d42abe0f287e60e4e5dedf5b49)

2023-05-31 18:55 UTC, HugeLetters commented on frontend/i18n/locales/ru/index.ts
>    }
Да пусть будет call-to-action - там же автокомплит в переводе все равно, печатать лишнего не придется.

2023-05-31 18:59 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/TextArea/TextArea.vue
сори, опять не поняла, ты предлагаешь убрать папку и оставить только сам файл TextArea?

2023-05-31 19:00 UTC, HugeLetters commented on frontend/assets/less/global.less
А `global.less` это не наши глобальные стили?

2023-05-31 19:01 UTC, HugeLetters commented on frontend/components/common/ui/TextArea/TextArea.vue
Посмотри коммит, который я выше линканул - так понятнее будет, мне кажется. У тебя компонент определно устаревшим синтаксом, Vue 3 рекомендует другой - я его уже сделал для твоей кнопки, но не для 2 других компонентов, сделанных тобой.

2023-05-31 19:02 UTC, Yulia-Kotlyarova commented on frontend/assets/less/global.less
да, но они не в скопе этой задачи

2023-05-31 19:03 UTC, HugeLetters commented on frontend/assets/less/global.less
Все так, я чисто к слову идею вкинул, тк не первый раз вижу, как туда пишут всякие поправки подобного рода, которые в принципе у ТВ уже есть.

2023-05-31 19:04 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +<script lang="ts">
Перепиши пожалуйста на script setup

2023-05-31 19:05 UTC, bigKingPenguin commented on frontend/components/common/ui/TextArea/TextArea.vue
> +<script lang="ts">
тоже нужно переписать на script setup

2023-05-31 19:06 UTC, HugeLetters commented on frontend/components/common/ui/BaseInput/BaseInput.vue
> +function updateValue(event: Event) {
У нас тут нету ссылок на this - разве есть разница?

2023-05-31 19:07 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseInput/BaseInput.vue
> +function updateValue(event: Event) {
давайте во имя единообразия

2023-05-31 19:10 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseInput/BaseInput.vue
> +function updateValue(event: Event) {
я имею ввиду const updateValue = (event: Event) => {

2023-06-01 09:22 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/TextArea/TextArea.vue
поправила, проверку типов в экшенах прошел, но у меня какие-то локальные проблемы в вебшторме из-за этого поставила игнор над типами

2023-06-01 09:22 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
+

2023-06-01 09:23 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +		<base-input
поправила

2023-06-01 09:23 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +<script lang="ts">
поправила

2023-06-01 09:23 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseInput/BaseInput.vue
> +function updateValue(event: Event) {
поправила

2023-06-01 09:23 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/TextArea/TextArea.vue
> +<script lang="ts">
поправила

2023-06-01 09:23 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseInput/BaseInput.vue
> +function updateValue(event: Event) {
поправила

2023-06-01 12:34 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseInput/BaseInput.vue
> +<script>
ts орет из-за 2х тегов скрипт
для чего этот код? 
export default {
	inheritAttrs: false
};

2023-06-01 12:47 UTC, bigKingPenguin approved these changes

2023-06-01 13:26 UTC, merged

2023-06-01 13:26 UTC, bigKingPenguin commented
#213