#213 refactor: base select
openworld-community/ows-events pull request #251
Opened 2023-06-01 17:44 UTC by Yulia-Kotlyarova

2023-06-02 07:47 UTC, bigKingPenguin requested changes

2023-06-02 07:47 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +// @ts-ignore
Я нашла, вот так тайпскрипт не ругается:
<img width="622" alt="Снимок экрана 2023-06-02 в 10 42 12" src="https://github.com/openworld-community/ows-events/assets/124285205/f37457fe-66fb-40a0-9984-75d5f93bc9ad">

2023-06-02 07:47 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +	console.log('isOpen', isOpen.value)
console.log)

2023-06-02 16:40 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +// @ts-ignore
Я так поняла это устаревший синтаксис, которого мы хотим избежать?

2023-06-03 16:31 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +// @ts-ignore
Если на WithDefaults ругается, давай будем писать так и не париться: 
const props = defineProps({
	className: {
		type: String as PropType<string>,
		default: ''
	},
	modelValue: { 
    type: String as PropType<string>,
    default: '' 
  },
	list: { 
    type: Array as PropType<string[]>,
    required: true 
  },
	name: { 
    type: String as PropType<string>, 
    required: true 
  },
	placeholder: { 
    type: String as PropType<string>,
    default: '' 
  },
	label: { 
    type: String as PropType<string>, 
    default: '' 
  },
	error: { 
    type: String as PropType<string>, 
    default: '' 
  },
	disabled: { 
    type: Boolean as PropType<boolean>,
    default: false 
  }
});

2023-06-03 16:36 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +    @click="setIsOpen()"
вызов функции тоже не обязательно писать, можно просто setIsOpen

исключением является случай, когда ты используешь тернарник isOpen ? close() : open()

2023-06-03 16:36 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +		<div :class="`select__list-box ${isOpen.value ? 'isOpen' : ''}`">
в  html разметке у ref и computed не нужно добавлять .value правильный вариант был isOpen

2023-06-06 16:48 UTC, closed without merging