#213 datepicker
openworld-community/ows-events pull request #281
Opened 2023-06-03 08:54 UTC by Yulia-Kotlyarova

Добавила дейтпикер
немного отрефакторила инпут и селектор

2023-06-03 17:03 UTC, bigKingPenguin requested changes

2023-06-03 17:03 UTC, bigKingPenguin commented on frontend/components/common/ui/Datepicker/Datepicker.vue
> +	<div class="className">
этот класс должен быть динамическим

2023-06-03 17:03 UTC, bigKingPenguin commented on frontend/components/common/ui/Datepicker/Datepicker.vue
> +withDefaults(defineProps<Props>(), {
давай тогда тоже переделаем, как в селекте

2023-06-06 10:08 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/Datepicker/Datepicker.vue
> +	const day = date.getDate();
вынесла

2023-06-06 10:08 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/Datepicker/Datepicker.vue
> +	<div class="className">
ок

2023-06-06 10:08 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/Datepicker/Datepicker.vue
> +withDefaults(defineProps<Props>(), {
ок

2023-06-06 16:48 UTC, merged