#213 datepicker
openworld-community/ows-events pull request #349
Opened 2023-06-12 17:53 UTC by Yulia-Kotlyarova

add search into select

2023-06-12 19:02 UTC, bigKingPenguin requested changes

2023-06-12 19:02 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +						@click.prevent="onRemove"
pevent здесь точно нужен?

2023-06-12 19:41 UTC, Yulia-Kotlyarova commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +						@click.prevent="onRemove"
это кнопка, может спровоцироваться саммит формы

2023-06-13 14:50 UTC, bigKingPenguin commented on frontend/components/common/ui/BaseSelect/BaseSelect.vue
> +						@click.prevent="onRemove"
а, окей

2023-06-13 14:53 UTC, bigKingPenguin approved these changes

2023-06-13 15:34 UTC, merged