#350 refactor Event Modal with new inputs
openworld-community/ows-events pull request #361
Opened 2023-06-14 12:34 UTC by Yulia-Kotlyarova

заменила инпуты на новые

2023-06-14 16:34 UTC, bigKingPenguin requested changes
отписалась по багам в лс

2023-06-16 08:28 UTC, HugeLetters commented
Для себя
TODO:
1. надо наверное прикрутить крестик на закрытие, когда list-box открыт, и закрытие list-box при клике мимо, потому что его никак не закрыть, не выбрав вариант
1. потерялось автоматическое подставление таймзоны
1. в отправке формы тоже что-то сломалось, но возможно из-за нерабочих таймзон
2. И в макете еще звездочками отмечены обязательные для заполнения поля, тоже добавить нужно

2023-06-17 23:38 UTC, Bambukoz approved these changes

2023-06-17 23:40 UTC, bigKingPenguin approved these changes

2023-06-17 23:41 UTC, merged