Fix types in country/city inputs
openworld-community/ows-events pull request #447
Opened 2023-06-21 16:43 UTC by bigKingPenguin

2023-06-22 00:43 UTC, HugeLetters reviewed
Я вообще не понимаю, что тут фиксится - все типы и без этих as у меня совершенно корректно подцепляются. Ну и если в терминале прогнать тайп-чекинг, то он тоже скажет, что все ок - как и аналогичная проверка при коммитах.

Касаемо дефолта и типа у props.list - все ок.

2023-06-22 08:45 UTC, bigKingPenguin commented
у меня редактор ругается, может ли это быть локальной проблемой вебшторма?

2023-06-22 10:17 UTC, Bambukoz approved these changes

2023-06-22 10:43 UTC, HugeLetters commented
> у меня редактор ругается, может ли это быть локальной проблемой вебшторма?

это сто процентов проблема вебшторма, если сам скрипт на тайпчекинг не ругается при этом.

2023-06-22 10:51 UTC, HugeLetters commented
Судя по всему у вебшторма какие-то траблы с инфером типов в авто-импортируюмых модулях или чето такое
https://intellij-support.jetbrains.com/hc/en-us/community/posts/8990772259730-WebStorm-Nuxt-3-TypeScript-not-working-in-template
https://youtrack.jetbrains.com/issue/WEB-58600/Nuxt-useFetch-result-type-not-inferred-when-using-Prisma
https://youtrack.jetbrains.com/issue/WEB-56524/The-types-of-refs-in-templates-are-unknown-when-using-auto-import-plugin

Я так понимаю, в том числе и поэтому ты и Юля постоянно импортируете всякие PropType, ref, computed и тд, хотя мне этого делать не приходится, потому что в моей ИДЕ корректно типизируются авто-импорты.

2023-06-22 10:57 UTC, bigKingPenguin commented
Пока оставлю тут этот реквест, попробую с вебштормом разобраться

2023-06-22 11:33 UTC, HugeLetters requested changes
pending

2023-06-28 11:21 UTC, bigKingPenguin commented
Проблема была в старой версии webshtorm, после обновления редактора проблемы с типами и импортами исчезли

2023-06-28 11:21 UTC, closed without merging