Fix/489 forbid edit old event
openworld-community/ows-events pull request #531
Opened 2023-06-28 07:52 UTC by Yulia-Kotlyarova

2023-06-28 07:57 UTC, HugeLetters commented on frontend/pages/event/[id].vue
> +const isEdible = computed(() => {
Съедобный?))

2023-06-28 08:01 UTC, HugeLetters commented on frontend/pages/event/[id].vue
Не против если я перепишу вот так?
```typescript
const posterEvent = computed(() => {
	if (!data.value) return void navigateTo({ name: RouteNameEnum.HOME });
	return data.value;
});

const isEditable = computed(() => {
	if (!posterEvent.value) return false;
	return posterEvent.value.date > Date.now();
});
```

2023-06-28 08:05 UTC, HugeLetters commented on frontend/pages/event/[id].vue
@bigKingPenguin за что голосуешь?

2023-06-28 08:06 UTC, HugeLetters commented on frontend/pages/event/[id].vue
> имхо лучше иф елсы, так лучше читается isEditable уже название поправила

если оставим твой вариант, поправь тогда, пожалуйста, лишние optional chains `?.`
`data` всегда есть, это `data.value` возможно null. Аналогично с `posterEvent`

2023-06-28 09:02 UTC, bigKingPenguin approved these changes

2023-06-28 09:02 UTC, bigKingPenguin commented on frontend/pages/event/[id].vue
Здесь маленькое совсем условие, в одну строку читается легче, как мне кажется. Я бы на самом деле для всех несложных сравнений так оставила

2023-06-28 09:13 UTC, Yulia-Kotlyarova commented on frontend/pages/event/[id].vue
убрала лишние операторы

2023-06-28 10:22 UTC, HugeLetters requested changes

2023-06-28 10:22 UTC, HugeLetters commented on frontend/pages/event/[id].vue
> +	return posterEvent.value?.date ? posterEvent.value.date > new Date().getTime() : false;
просто так тогда по идее
`return posterEvent.value ? posterEvent.value.date > Date.now() : false;`

2023-06-29 08:08 UTC, Yulia-Kotlyarova commented on frontend/pages/event/[id].vue
> +	return posterEvent.value?.date ? posterEvent.value.date > new Date().getTime() : false;
+

2023-06-29 08:35 UTC, bigKingPenguin approved these changes

2023-06-29 09:43 UTC, HugeLetters approved these changes

2023-06-29 10:16 UTC, bigKingPenguin commented
Посмотри пожалуйста конфликты, и потом можно смержить

2023-06-29 10:57 UTC, il12 commented
Пожалуйста, множитель ветки с фиксами фич в ветку с самой фичой!

2023-06-29 11:31 UTC, bigKingPenguin commented
Это скорее не фикс, это заведенный в тасках баг. Ветка была создана раньше, чем мы описали процесс

2023-06-29 11:32 UTC, il12 commented
> Это скорее не фикс, это заведенный в тасках баг. Ветка была создана раньше, чем мы описали процесс

Тогда все ок, прошу прощения

2023-06-29 14:08 UTC, merged