DRAFT: St 521 user page html and css
openworld-community/ows-events pull request #541
Opened 2023-06-28 16:53 UTC by MissShim

Действительно черновик. Мне надо сделать несколько уточнений, прежде чем с моей стороны это задание будет финализоровано. Я просто подумала, что лучше будет делать уточнения на основе уже имеющейся верстки, чем просто на словах.
1. Во-первых, я сверстала это, как форму. Это окей? Просто по-сути это же форма, но уже заполненная. Но я не уверена, может, раз тут всё статично, надо было просто дивами и параграфами сверстать? О_о
2. Касательно "В тех местах, в которые должен динамически вставляться текст, оставить рандомные заглушки" -  не уверена, что именно лучше для "заглушки" использовать: атрибут placeholder или value? наверное, тут скорее подходит value? Но стили для placeholder я пока на всякий случай добавила.
3. Не уверена, какую тень и цвет бордера использовать для инпутов. Когда копирую цвета макета из фигмы, то в моём браузере цвета выглядят намного темнее. Поэтому я там оставила в коде запасной вариант тени для инпута, который подбирала на глаз, чтобы смотрелось, как в макете. Но в итоге мне просто надо знать, какой из вариантов остаить.
4. Не было всех нужных переменных для паддингов в инпутах. Я не стала их заводить, потому что сначала решила убедится, что мой вариант верстки через форму с инпутами вообще подходит. 

Вроде всё.

2023-06-29 08:54 UTC, bigKingPenguin requested changes
По сути только теги поменять, в остальном все отлично)

2023-06-29 08:54 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +	//box-shadow: 0px 1px 6px 0px rgba(78, 78, 78, 0.15);  <--Изначальный вариант тени, т.к. мне кажется, что в итоге получилось темнее, чем на макете
Может ребята поправили, но сейчас на макете 
`box-shadow: 0px 2px 6px 0px rgba(78, 78, 78, 0.5);`
Пока не очень принципиально, потому что они вроде бы еще хотели поправить эти параграфы - посмотрим, как у них будет. Оставь пока все варианты

2023-06-29 09:40 UTC, bigKingPenguin commented
И наверное пока лучше оставить только никнейм в телеграм, имя и компанию. Остальные поля будем добавлять потом по мере необходимости

2023-06-30 17:29 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +	&__fieldset {
Здесть еще дополнительно:

`overflow-y: auto`

2023-06-30 17:29 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +	margin-bottom: auto;
для .user-page еще добавить: 

`max-height: calc(100vh - var(--header-height));`


 `    @supports (-webkit-touch-callout: none) {
		max-height: -webkit-fill-available;
	}
`

2023-06-30 17:29 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +			<h2 class="user-page__title">{{ $t('user.title_profile') }}</h2>
заголовок лучше вынести выше за пределы дива

2023-06-30 19:16 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +const props = defineProps<Props>();
вот эту штуку тоже удаляем, потому что пропс определяется внутри модалки

2023-06-30 19:16 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +				@click="props.logout"
здесь можно просто дернуть вызов функции 
`logout`

а в скрипте пока создать эту функцию, которая будет выводить что-нибудь в консоль

2023-07-03 13:24 UTC, bigKingPenguin commented on frontend/components/modal/EditProfile.vue
> +					@click="props.closeEditProfileModal"
Сюда теперь можно добавить вызов функции updateUserData и описать ее в скрипте (пока можно вывести что-то в консоль внутри нее и затем дернуть функцию, закрывающую модал), когда будет готов бэк, в этой функции будет отправка данных на сервер

2023-07-03 13:24 UTC, bigKingPenguin commented on frontend/i18n/locales/ru/index.ts
> +		nickname: 'Никнейм',
Давай переименуем в "Логин", потому что потом, когда прикрутим авторизацию через гугл аккаунт, здесь будет либо ник в тг, либо гугл почта

2023-07-03 13:24 UTC, bigKingPenguin commented on frontend/i18n/locales/ru/index.ts
> +				nickname: 'Никнейм',
а в модале нам никнейм-логин не нужен будет

2023-07-03 13:24 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +	console.log('Здесь должен происходить выход из аккаунта');
вот сюда уже можно переносить содержимое функции deauthorize из components/header/Authorization.vue

2023-07-04 13:26 UTC, bigKingPenguin reviewed
Апрув на этом этапе, теперь ждем бэк

2023-07-04 16:59 UTC, bigKingPenguin commented on frontend/i18n/locales/ru/index.ts
> +			login: 'Войти с помощью Telegram'
добавила для aria-label

2023-07-04 16:59 UTC, bigKingPenguin commented on frontend/pages/postauth/[id].vue
> +await navigateTo({ name: RouteNameEnum.USER_PAGE });
теперь при авторизации идет редирект на юзерпейдж

2023-07-04 16:59 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +		<template v-if="isAuthorized">
если нужно только повесить проверку, то для этого хорошо использовать тег template (при рендеринге он не отображается в DOM, а значит нет лишних дивов)

2023-07-04 16:59 UTC, bigKingPenguin commented on frontend/pages/user.vue
> +		<div
я вынесла нативную кнопку из user-page__actions, чтобы отцентровать посередине страницы (когда у нас добавятся другие способы авторизации, они будут красиво в столбик висеть по центру)

2023-08-24 12:36 UTC, Bambukoz approved these changes

2023-08-24 12:37 UTC, bigKingPenguin approved these changes

2023-08-24 13:07 UTC, merged