add first version of donate page
openworld-community/ows-events pull request #576
Opened 2023-07-10 04:47 UTC by orby-tech

2023-07-10 04:51 UTC, orby-tech commented
![image](https://github.com/openworld-community/ows-events/assets/59844758/f2f77bbe-c7e5-462f-a5fb-c9d3ac9cc1a3)

2023-07-11 20:06 UTC, il12 approved these changes

2023-07-11 20:36 UTC, Bambukoz requested changes

2023-07-11 20:36 UTC, Bambukoz commented on frontend/assets/less/colors.less
> +  --color-donate-icon-patreon: #FF424D;
-icon- в неймах лишнее, т.к. ты потом можешь его не только на иконки распространять

2023-07-11 20:36 UTC, Bambukoz commented on frontend/i18n/locales/ru/donate.ts
> +		'\t\t\tВаша поддержка позволит нам развивать проект, расширять его\n' +
так не надо делать
лучше разбивать на строчки и вставлять частями в разметку, либо вставлять такие тексты с html разметкой и вставлять такой перевод через v-html (но перед этим нужно еще прикрутить и настроить sanitize для html, например https://www.npmjs.com/package/nuxt-sanitize-html)

2023-07-11 20:56 UTC, bigKingPenguin commented on frontend/assets/less/colors.less
> +  --color-donate-icon-patreon: #FF424D;
готово

2023-07-11 20:57 UTC, bigKingPenguin commented on frontend/i18n/locales/ru/donate.ts
> +		'\t\t\tВаша поддержка позволит нам развивать проект, расширять его\n' +
пока убрала автоформат в файле переводов, создала таск на добавление санитайзера

2023-07-11 20:58 UTC, Bambukoz approved these changes

2023-07-11 20:58 UTC, merged